#!/bin/bash

#create file Test_file
touch Test_file


#changing file permission to make it readable and writable by user
chmod 600 Test_file

#changing file permission to make it readable by the group
chmod 640 Test_file

#No permission for other 
chmod 640 Test_file

#showing above permission
ls -l Test_file

#opening the Test_file
gedit Test_file &
disown

#opening firefox and github in it
firefox http://github.com & 
disown
